# Generated by Django 4.0.6 on 2022-07-25 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('payment_method', models.CharField(max_length=100)),
                ('order_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
